name: dotnet-ci-branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore MineSweeper
    - name: Build
      run: dotnet build --no-restore MineSweeper --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal MineSweeper --configuration Release
