name: Generar Juego de Serpientes de Contribución

on:
  schedule:
    - cron: '0 0 * * *' # Ejecuta todos los días a medianoche

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generar Juego de Serpientes
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9